[package]
name = "winternitz"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
sha2 = "0.10.8"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "wots_benchmarks"
harness = false
